#!/bin/bash
JS_HOME=`pwd`/${0%/*}
JSCLASSPATH=${JS_HOME}/lib/antlr.jar:${JS_HOME}/lib/google-collect-1.0.jar:lib/javabdd-1.0b2.jar:${JS_HOME}/bin
case `uname` in
    CYGWIN*)
        JSCLASSPATH=`cygpath -p -w -m -s "$JSCLASSPATH"`
	JS_HOME=`cygpath -p -w -m -s "$JS_HOME"`
        ;;
    *)
esac
if [ `uname -m` = "x86_64" ]; then
    JMEM_OPTS="-Xms1g -Xmx3g"
else
    JMEM_OPTS="-Xms512m -Xmx1000m"
fi

java ${JMEM_OPTS} -ea -cp "${JSCLASSPATH}" org.jakstab.Main $*
